openapi: 3.0.3

info:
  title: Test PPNS Multibox
  version: '1.0'
  description: |
    # Overview
    This API is for the HMRC API Platform developers to test migration to PPNS multibox.

servers:
- url: https://test-api.service.hmrc.gov.uk/test/ppns-multibox
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/test/ppns-multibox
  description: Production

tags:
- name: test-ppns-multibox
  description: 'Test PPNS Multibox Tag'
  
components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json",
          "application/vnd.hmrc.1.0+xml"
        ]
      required: true
  schemas:
    TimeResponse:
      title: Current Time Response
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: 2023-02-27T16:54:23.933430Z

paths:
  /current-time:
    get:
      tags:
      - test-ppns-multibox
      summary: Return the current time
      description: >
        An endpoint that returns the current server time.
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        '200':
          description: 'OK Response'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TimeResponse'
      security:
      - {}
