openapi: 3.0.3

info:
  title: Test PPNS Multibox
  version: '1.0'
  description: |
    # Overview
    This API is for the HMRC API Platform developers to test migration to PPNS multibox.

servers:
- url: https://test-api.service.hmrc.gov.uk/test/ppns-multibox
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/test/ppns-multibox
  description: Production

tags:
- name: test-ppns-multibox
  description: 'Test PPNS Multibox Tag'
  
components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json",
          "application/vnd.hmrc.1.0+xml"
        ]
      required: true
  schemas:
    TimeResponse:
      title: Current Time Response
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: 2023-02-27T16:54:23.933430Z
    NotificationResponse:
      title: Notification Response
      required:
        - boxId
        - correlationId
      type: object
      properties:
        boxId:
          type: string
        correlationId:
          type: string
      example:
        boxId: f9e722a8-200c-4572-8680-aa3f103ea1a5
        correlationId: 2bb5b059-73db-4445-a7ae-4e4c471866dd

paths:
  /current-time:
    get:
      tags:
      - test-ppns-multibox
      summary: Return the current time
      description: >
        An endpoint that returns the current server time.
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        '200':
          description: 'OK Response'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TimeResponse'
      security:
      - {}

  /notify-me-in:
    get:
      tags:
        - test-ppns-multibox
      summary: Take minutes to return the current time
      description: >
        An endpoint that takes the requested number of minutes to return the current server time.
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - in: path
          name: minutes
          schema:
            type: integer
          required: true
          description: Number of minutes to notification
      responses:
        '202':
          description: 'ACCEPTED Response'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/NotificationResponse'
      security:
        - {}